Разметка главной страницы
htmlacademy-htmlcss/1705973-technomart-30 pull request #2
Opened 2021-01-23 12:40 UTC by Belladonna26

2021-01-23 14:30 UTC, mikhailmaclay requested changes

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +          <a href="blank.html">
В техническом задании не увидел, что клик по заголовку или изображению должен вести на страницу товара. Придерживаемся принципа YAGNI и выпиливаем ссылку.

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +            <button type="button">15500Р."</button>
Пробел после суммы

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +
Все содержимое карточки лучше обернуть в `div`

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +            <del>22500</del><br>
Потерялась буква Р после суммы

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +        <del>22500</del><br>
Потерялась буква Р после суммы

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +        <button type="button">12500Р."</button>
Смотрим комментарии к 116 строчке

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +</p>
Лишняя обертка для изображения

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  <img src="img/object.png" width="126" height="37" alt="logo Bosch">
Необходимо соблюдать единообразие, поэтому `logo` заменяем на `Логотип`

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +<h3>Bosch</h3>
Заголовок тут лишний, достаточно ссылки, оборачивающей изображение

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  </a>
Ниже карточки производителей не смотрю

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +    <p>Хороший интернет-магазин отличается от плохого не только ценами!<br>
Можно будет обойтись без `br`

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  </select>
На данный момент могу сказать, что, скорее всего, это будет обернутый список с кнопками

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +</section>
Это подсекция предыдущей секции

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  <b>КОМПАНИЯ "ТЕХНОМАРТ"</b>
Я так понимаю, что вы решили сделать `h2` скрытым заголовком, а `b` визуальным?

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для<br>
Думаю, что пока можно обойтись без `br`  во всем абзаце

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  <img src="img/object.png" width="25" height="2" alt="line"> ЖелДорЭкспедиция<br>
Это список со стилизованными маркерами. Изображения убираем.

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  <img src="img/object.png" width="25" height="2" alt="line"> ЖелДорЭкспедиция<br>
Кстати, список нельзя вкладывать в `p`

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  <button type="button">ПОДРОБНЕЕ О КОМПАНИИ</button>
Это должна быть ссылка на отдельную страницу

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  <button type="button">ПОДРОБНЕЕ О КОМПАНИИ</button>
Кстати, не обязательно текст в разметке, если на макете он набран капсом, набирать капсом. Я рекомендую использовать для этого стили.

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +<a href="#">
ТЗ пункт 4.3. Это должна быть кнопка, открывающая модальное окно.

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  <p><img src="img/map.png" width="300" height="158" alt="карта"></p>
Снова лишняя обертка изображения

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +      <section>
Разделять `footer` на `section` уже не имеет смысла

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +      <a href="index.html">
Мы уже находимся на главной, поэтому атрибут `href` опускаем

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +         <img src="img/logo-technomart.png" width="108" height="18" alt="Логотип">
Смотрим на комментарий к 12 строке

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +  <a href="#">mail@htmlacademy.ru</a>
`href="mailto:mail@htmlacademy.ru"`

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +<p>
Придирка: Больше похоже на `span`

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +<p>Разработано-<br>
Придирка: Больше похоже на `span`

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +      <section>
Соответственно, заголовки здесь тоже не нужны

2021-01-23 14:30 UTC, mikhailmaclay commented on index.html
> +    <section>
Смотрим комментарии к строке 282

2021-01-23 15:26 UTC, Belladonna26 commented on index.html
> +</a>
правильно понимаю, у меня получается основная ошибка в списках и правильной должна быть след.последовательность?
<p>
<a>
<h> 
</h></a></p>? ну и в др местах соответственно чекну потом

2021-01-23 15:29 UTC, Belladonna26 commented on index.html
> +</a>
теги не печатаются судя по всему здесь?
последовательность: тег p, затем тег a, затем тег h

2021-01-23 15:29 UTC, Belladonna26 commented on index.html
> +  <img src="img/icon-search.png" width="17" height="17" alt="Иконка поиска">
Так всё-таки иконка поиска неидентична иконке корзины и закладок? Выходит мне нужно убрать только строчку с иконкой поиска?

2021-01-23 18:03 UTC, mikhailmaclay commented on index.html
> +  <img src="img/icon-search.png" width="17" height="17" alt="Иконка поиска">
Да, необходимо убрать иконку только здесь, так как мы будем ее задавать через `css`

2021-01-24 07:47 UTC, mikhailmaclay requested changes

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +</nav>
Поправить форматирование

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +
Придирка: Можно убрать пустую строку

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +
Придирка: Можно убрать пустую строку

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +</a>
Поправить форматирование

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +              <span>25500 Р."</span>
Лишние двойные кавычки

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +              <span>15500 Р."</span>
Лишние двойные кавычки

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +        <span>25500 Р."</span>
Лишние двойные кавычки

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +      <p>
Поправить форматирование

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +        <span>12500 Р."</span>
Лишние двойные кавычки

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +     </p>
Поправить форматирование

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +  <img src="img/object.png" width="123" height="40" alt="Логотип Mokita">
Опечатка `Makita`

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +  а если вставлять кнопку,то более сложная конструкция, но в наших мат-ах про это нет ничего пока что,не знаю надо ли вставлять сейчас -->
Да, это как один из вариантов реализации модальных окон. Расскажу об этом позже.

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +</p>
Лишняя обертка `p`

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +  <b>КОМПАНИЯ "ТЕХНОМАРТ"</b>
Лучше вынести из `b` перед `p`

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +заехав в наш офис:<br>
Этот последний `br` здесь не нужен. По критериям качества запрещено использовать `br` для формирования отступов.

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +  а если вставлять кнопку,то более сложная конструкция, но в наших мат-ах про это нет ничего пока что,не знаю надо ли вставлять сейчас -->
Комментарий удаляем, в финальном коде скрипя зубами можно только TODO-комментарии оставить

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +    </main>
(╯‵□′)╯︵┻━┻

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +<a href="#">Закладки:0>
Потеряли пробел после `:`

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +<a href="#">Корзина:0>
Потеряли пробел после `:`

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +  <img src="img/icon-bookmark.png" width="14" height="16" alt="Иконка закладок">
Иконка должна быть перед текстом

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +  <img src="img/icon-bookmark.png" width="14" height="16" alt="Иконка закладок">
Перепроверить повторяющиеся случаи ниже

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +<a href="#">Оформить заказ</a>
А почему здесь заглушка `#`, когда в проекте решили использовать ссылку на `blank.html`?

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +<a href="#">Оформить заказ</a>
Перепроверить повторяющиеся случаи ниже

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +            <img src="img/object2" width="184" height="164" alt="Перфоратор bosch bfg-3000">
Стоит соблюдать единообразие, если в заголовке `Перфоратор BOSCH BFG 3000`, то и в `alt` у `img` должно быть то же самое

2021-01-24 07:47 UTC, mikhailmaclay commented on index.html
> +            <img src="img/object2" width="184" height="164" alt="Перфоратор bosch bfg-3000">
Перепроверить повторяющиеся случаи выше и ниже

2021-01-24 12:50 UTC, mikhailmaclay commented on index.html
> +              <del>22500 Р.</del><br>
Лишний `br`

2021-01-24 12:51 UTC, mikhailmaclay commented on index.html
> +            <p>
Обертка не нужна

2021-01-25 09:24 UTC, mikhailmaclay requested changes
Страницу каталога не проверял. Необходимо внести исправления в разметку главной страницы.

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +    <p>Интернет-магазин
Придирка: Здесь бы текст перенести на следующую строку

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +      <button onclick="chooseLine(event, 'Delivery')">Доставка</button>
Что за функции в `onclick`?

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +      <p> Мы с удовольствием доставим ваш товар прямо
Лишний пробел после `p`

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +      <p> Мы с удовольствием доставим ваш товар прямо
Придирка: Здесь бы текст перенести на следующую строку

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +      <p>Если купленный у нас товар поломается или заискрит,
Придирка: Здесь бы текст перенести на следующую строку

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +      <p>Залезть в долговую яму стало проще!
Придирка: Здесь бы текст перенести на следующую строку

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +        КОМПАНИЯ "ТЕХНОМАРТ"
Говорили о том что это будет `b` вынесенный из `p` выше

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +        Техномарт работает со многими транспортными компаниями:</p>
Переносы. Проверь, пожалуйста, чтобы было единообразно везде.

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +      </p>
Зачем обертка?

2021-01-25 09:24 UTC, mikhailmaclay commented on index.html
> +      </p>
Зачем обертка?

2021-01-25 09:25 UTC, mikhailmaclay commented on catalog.html
> +                        <button onclick="#">Купить</button>
`onclick="#"`? Это что?

2021-01-25 09:25 UTC, mikhailmaclay commented on index.html
> +        <button onclick="#">ЗАБЛУДИЛИСЬ?НАПИШИТЕ НАМ!</button>
`onclick="#"`? Это что?

2021-01-25 09:32 UTC, mikhailmaclay commented on index.html
> +        КОМПАНИЯ "ТЕХНОМАРТ"
Плюс опять же, набран капсом

2021-01-25 09:38 UTC, mikhailmaclay commented on catalog.html
> +                        <button onclick="#">Купить</button>
В общем, эта штука не валидная, поэтому выпиливаем здесь и ниже

2021-01-25 17:34 UTC, mikhailmaclay requested changes

2021-01-25 17:34 UTC, mikhailmaclay commented on index.html
> +        <p>Мы с удовольствием доставим ваш товар прямо<br>
Снова кривой перенос. Пожалуйста, проверь чтобы везде после `p` был перенос строки.

2021-01-25 17:34 UTC, mikhailmaclay commented on index.html
> +          Дом уж восстановите как-нибудь сами.</p>
Здесь перед закрывающим тэгом тоже сделать разрыв

2021-01-25 17:34 UTC, mikhailmaclay commented on index.html
> +        Техномарт работает со многими транспортными компаниями:</p>
Перед `p` сделать разрыв

2021-01-25 17:34 UTC, mikhailmaclay commented on index.html
> +        Техномарт работает со многими транспортными компаниями:</p>
Перепроверь везде, пожалуйста

2021-01-25 17:34 UTC, mikhailmaclay commented on index.html
> +      <button type="button">Заблудились? Напишите нам!</button>
Тут важный вопрос, либо мы делаем реализацию через `button`, либо через `a`. Сразу скажу, что через `button` будет проще. Поэтому, как определишься, стоит в 265 написать соответствующий элемент и в 268 строке.

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +        <a href="index.html">
Здесь нужно добавить `aria-label` со значением `Главная страница` или `На главную`

2021-01-25 17:34 UTC, mikhailmaclay commented on index.html
> +    <a href="blank.html">Регистрация</a>
Оформляем в список

2021-01-25 17:34 UTC, mikhailmaclay commented on index.html
> +    <a href="blank.html">Регистрация</a>
Видел, что ты в странице каталога решила использовать еще один `nav`, Здесь этот список тоже можно будет в `nav` обернуть.

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +    <header>
Не забываем правки по `header` и `footer` на главной странице переносить сюда

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +        </nav>
Как говорил, на главной странице, это все можно завернуть в отдельную навигацию `nav`

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +            <li>Каталог</li>
Первый элемент это ссылка на главную страницу с иконкой

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                <p><span>0</span>-<span>30000</span></p>
```
<div>
  <!-- Полоска, на которой находятся кнопки -->
  <div>
    <button type="button" aria-label="Минимальная цена"></button>
    <button type="button" aria-label="Максимальная цена цена"></button>
  </div>
  <input type="number" min="0" max="40000">
  <input type="number" min="0" max="40000">
</div>
```

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                <p><span>0</span>-<span>30000</span></p>
Примерная разметка этого поля ввода

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +            <span>Фильтр:</span>
Неправильный порядок элементов, сначала идет `Фильтр`, а потом `Цена`. `Цена` не может быть заголовком, да и заголовок тут вообще не нужен.

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +            <span>Фильтр:</span>
`Цена` нужно переместить в форму в соответствующую обертку для группы полей ввода

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                <section>
`section` это элемент про содержимое страницы, про контент, а не поля формы. Здесь подойдет `fieldset`, но он туго стилизуется, поэтому лучше использовать `div`.

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                    <h2>Производители:</h2>
Заголовок здесь не нужен

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                            <label for="filter-bosch">Bosch</label>
`input` + `label` лучше обернуть в `div` или `span`

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                            <label for="filter-bosch">Bosch</label>
Ниже, разумеется, аналогично

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                    <h2>Питание:</h2>
Заголовок не нужен, используй `b` или `span`

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                            <label for="filter-bat">Аккумуляторные</label>
`input` + `label` лучше обернуть в `div` или `span`

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +                <button type="submit">Показать</button>
Кнопка, находящаяся в форме, и так будет ее отправлять по нажатию, поэтому атрибут `type` в значении `submit` не обязателен

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +        </ul>
Это называется Хлебные крошки. Их лучше вынести из `main` наверх.

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +            <h2>Цена</h2>
Здесь лучше будет сделать `h2` `Фильтр`.

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +        <h2>Перфораторы</h2>
Этот заголовок не имеет значения, если секциям Фильтр, Сортировка и Список товаров дать заголовок

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +            </a>
Можно оформить в список

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +            <a href="?page=4">Следующая</a>
Это называется Пагинация. Выносим ее вниз из этой секции.

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +            <a href="?page=4">Следующая</a>
Плюс оформляем в список

2021-01-25 17:34 UTC, mikhailmaclay commented on catalog.html
> +    <footer>
`footer` не проверяю, так как сделал это уже на главной странице

2021-01-27 14:46 UTC, mikhailmaclay approved these changes

2021-01-27 15:18 UTC, merged